#!/usr/bin/env node
// G2 sync gate — generates src/generated/models.ts from openapi/openapi.sdk.json.
//
// Zero dependencies (mirrors @lumifyai/mcp's philosophy): a small, purpose-built
// JSON-Schema-subset -> TypeScript translator, not a general OpenAPI codegen. It
// only needs to understand the shapes FastAPI/Pydantic actually emit for this
// API (see scripts/export_openapi_sdk.py at the repo root), which are: object
// schemas with `properties`/`required`, `$ref`, `anyOf` (used for nullable),
// `array` + `items`, and the primitive scalar types.
//
// Usage:
//   node scripts/gen-models.mjs            write src/generated/models.ts
//   node scripts/gen-models.mjs --check    exit 1 if the file is stale
//
// Run whenever openapi/openapi.sdk.json changes (regenerate it first with
// `python scripts/export_openapi_sdk.py` from the repo root).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = join(__dirname, "..");
const SCHEMA_PATH = join(PKG_ROOT, "openapi", "openapi.sdk.json");
const OUTPUT_PATH = join(PKG_ROOT, "src", "generated", "models.ts");

function loadSchema() {
  const raw = readFileSync(SCHEMA_PATH, "utf8");
  return JSON.parse(raw);
}

/** Map a JSON Schema fragment to a TypeScript type expression. */
function tsType(node) {
  if (!node) return "unknown";
  if (node.$ref) return refName(node.$ref);

  if (Array.isArray(node.anyOf)) {
    const parts = node.anyOf.map(tsType).filter((v, i, arr) => arr.indexOf(v) === i);
    return parts.join(" | ") || "unknown";
  }

  switch (node.type) {
    case "integer":
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `Array<${tsType(node.items)}>`;
    case "object":
      if (node.properties) return objectLiteral(node);
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function refName(ref) {
  return ref.split("/").pop();
}

function objectLiteral(node) {
  const required = new Set(node.required || []);
  const props = node.properties || {};
  const fields = Object.entries(props)
    .map(([key, val]) => `${propKey(key)}${required.has(key) ? "" : "?"}: ${tsType(val)}`)
    .join("; ");
  return `{ ${fields}${fields ? "; " : ""}[key: string]: unknown }`;
}

function propKey(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

/** Real prose only — the auto-generated `title` (e.g. "Credits Used") is just
 * the field name title-cased and adds no information, so it's intentionally
 * not surfaced here. */
function jsdoc(node) {
  return node.description ? node.description.trim() : null;
}

function genInterface(name, schema) {
  const lines = [];
  const doc = jsdoc(schema);
  if (doc) lines.push(`/** ${doc} */`);

  if (schema.type !== "object" && !schema.properties) {
    // Non-object top-level schema (rare) — fall back to a type alias.
    lines.push(`export type ${name} = ${tsType(schema)};`);
    return lines.join("\n");
  }

  const required = new Set(schema.required || []);
  const props = schema.properties || {};
  lines.push(`export interface ${name} {`);
  for (const [key, val] of Object.entries(props)) {
    const doc2 = jsdoc(val);
    if (doc2) lines.push(`  /** ${doc2} */`);
    lines.push(`  ${propKey(key)}${required.has(key) ? "" : "?"}: ${tsType(val)};`);
  }
  if (schema.additionalProperties) {
    lines.push(`  [key: string]: unknown;`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

function build(schema) {
  const schemas = (schema.components && schema.components.schemas) || {};
  const names = Object.keys(schemas).sort();

  const header = `// AUTO-GENERATED by scripts/gen-models.mjs from openapi/openapi.sdk.json.
// Do not edit by hand — run \`npm run gen:models\` after regenerating the schema
// with \`python scripts/export_openapi_sdk.py\` at the repo root.
//
// This is the SDK's data-model layer (sync gate G2): every interface here maps
// 1:1 to a component schema in the live OpenAPI contract, so response shapes
// can never silently drift from the API.
`;

  const body = names.map((name) => genInterface(name, schemas[name])).join("\n\n");
  return `${header}\n${body}\n`;
}

function main() {
  const schema = loadSchema();
  const content = build(schema);

  const check = process.argv.includes("--check");
  if (check) {
    let current = "";
    try {
      current = readFileSync(OUTPUT_PATH, "utf8");
    } catch {
      // missing file -> treated as stale below
    }
    if (current !== content) {
      process.stderr.write(`${OUTPUT_PATH} is stale. Run: node scripts/gen-models.mjs\n`);
      process.exitCode = 1;
      return;
    }
    process.stdout.write(`${OUTPUT_PATH} is up to date.\n`);
    return;
  }

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, content);
  const schemaCount = Object.keys((schema.components || {}).schemas || {}).length;
  process.stdout.write(`Wrote ${OUTPUT_PATH} (${schemaCount} models)\n`);
}

main();
