# AUTO-GENERATED by scripts/gen_models.py from the shared OpenAPI slice
# clients/lumify-sdk/openapi/openapi.sdk.json (produced by
# scripts/export_openapi_sdk.py at the repo root). Do not edit by hand —
# run `python scripts/gen_models.py` after regenerating the schema.
#
# This is the SDK's data-model layer (sync gate G2): every TypedDict here
# maps 1:1 to a component schema in the live OpenAPI contract — the SAME
# artifact the TypeScript SDK generates from — so response shapes can never
# silently drift from the API or between the two SDKs.

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

try:  # TypedDict is in typing on 3.8+, but this keeps intent explicit.
    from typing import TypedDict
except ImportError:  # pragma: no cover - Python < 3.8 unsupported
    from typing_extensions import TypedDict  # type: ignore


__all__ = [
    "AgentApiKey",
    "AgentApiKeyListResponse",
    "AgentApiKeyRevokeResponse",
    "AgentCreditsResponse",
    "BatchEventsRequest",
    "BatchEventsResponse",
    "BetIntelligence",
    "CreditPack",
    "CreditPackListResponse",
    "CreditTopupResponse",
    "EstimateCall",
    "EstimateRequest",
    "EstimateResponse",
    "EstimateResult",
    "EventDetail",
    "EventListResponse",
    "EventSummary",
    "HTTPValidationError",
    "IntelligenceResponse",
    "LeagueSummary",
    "MlbStatsHeadToHead",
    "MlbStatsHeadToHeadMeeting",
    "MlbStatsLineup",
    "MlbStatsLineupPlayer",
    "MlbStatsRatesBlock",
    "MlbStatsRecentForm",
    "MlbStatsRecord",
    "MlbStatsResponse",
    "MlbStatsStartingPitcher",
    "MlbStatsTeam",
    "MlbStatsTeams",
    "MlbStatsWindows",
    "NLQueryFilters",
    "NLQueryRequest",
    "NLQueryResponse",
    "OddsHistoryResponse",
    "OddsResponse",
    "Participant",
    "Player",
    "PlayerEventsResponse",
    "PlayersListResponse",
    "ScoreEntry",
    "ScoreResponse",
    "Season",
    "SeasonSummary",
    "SeasonsListResponse",
    "SplitsResponse",
    "Sport",
    "SportsListResponse",
    "StatsHeadToHead",
    "StatsHeadToHeadMeeting",
    "StatsLeagueContext",
    "StatsLineup",
    "StatsLineupPlayer",
    "StatsRatesBlock",
    "StatsRecentForm",
    "StatsResponse",
    "StatsSos",
    "StatsTeam",
    "StatsTeams",
    "StatsWindows",
    "Team",
    "TeamsListResponse",
    "TrialKeyRequest",
    "ValidationError",
    "WebhookCreateResponse",
    "WebhookDeleteResponse",
    "WebhookDeliveryItem",
    "WebhookDeliveryListResponse",
    "WebhookListResponse",
    "WebhookSubscription",
]


class AgentApiKey(TypedDict, total=False):
    id: Optional[int]
    name: Optional[str]
    key_prefix: Optional[str]
    scopes: Optional[List[str]]
    created_at: Optional[str]
    last_used_at: Optional[str]
    expires_at: Optional[str]
    is_active: Optional[bool]
    key: Optional[str]
    """Full API key — returned once on create."""


class AgentApiKeyListResponse(TypedDict, total=False):
    data: List[AgentApiKey]
    total: int


class AgentApiKeyRevokeResponse(TypedDict, total=False):
    revoked: bool
    id: Optional[int]


class AgentCreditsResponse(TypedDict, total=False):
    tier: Optional[str]
    credits_used: Optional[int]
    credit_limit: Optional[int]
    bonus_credits: Optional[int]
    total_remaining: Optional[int]
    period_start: Optional[str]
    period_end: Optional[str]
    is_trial: Optional[bool]
    is_trial_expired: Optional[bool]


class BatchEventsRequest(TypedDict, total=False):
    event_ids: List[int]
    """Event ids to fetch (max 25). Duplicates are billed once."""
    include_odds: bool
    """Inline current odds on each event. Scoped by bookmaker (default: pinnacle). +1 credit per event for a single book when available; +2 for bookmaker=all or a comma-separated list."""
    include_intelligence: bool
    """Inline bet intelligence on each event (+1 credit per event when available)."""
    bookmaker: Optional[str]
    """Bookmaker for inlined odds and intelligence market prices. Defaults to pinnacle; 'all' or a comma-separated list for multiple books."""


class BatchEventsResponse(TypedDict, total=False):
    events: List[EventDetail]
    not_found: List[int]
    """Requested event_ids that don't exist. Never billed."""
    total: int


class BetIntelligence(TypedDict, total=False):
    bet_type: Optional[str]
    """Canonical bet token, e.g. ML_HOME/ML_AWAY/ML_DRAW (soccer), ML_P1/ML_P2 (head-to-head sports), SPREAD_HOME/SPREAD_AWAY, OVER, UNDER."""
    player_role: Optional[str]
    """'home'/'away' for team sports or 'p1'/'p2' for head-to-head sports. Null for match-level tokens (OVER, UNDER, ML_DRAW), which are not about either side."""
    player_id: Optional[int]
    """Player ID when this bet is about an individual player; null for team bets and match-level tokens (OVER, UNDER, ML_DRAW)."""
    team_id: Optional[int]
    """Team ID when this bet is about a team; null for individual-player bets and match-level tokens (OVER, UNDER, ML_DRAW). A draw is not a bet on either team, so ML_DRAW carries no team_id — safe to sum exposure by team_id across bets without double-counting the draw."""
    player_name: Optional[str]
    """Display name of the player or team this bet is about; null for match-level tokens (OVER, UNDER, ML_DRAW). Duplicates `players[player_role].name` for convenience when flattening bets[]."""
    market: Optional[Dict[str, Any]]
    """Market quote used for this bet: {price: American odds, line: handicap/total line or null for moneyline, book: bookmaker slug when known}. For predictive-framework sports `book` is always populated from the assessment; for legacy sports it may be omitted. Present for every sport."""
    computed_at: Optional[str]
    """ISO-8601 UTC timestamp of when this bet's numbers last materially changed — not when they were last checked. The publisher re-runs on a schedule but only rewrites a row when the price, line, or probability moves beyond a tolerance, so an older `computed_at` means 'unchanged since', not 'stale'. Values legitimately differ between bets on the same event because each market moves independently."""
    tier: Optional[str]
    """Confidence tier: 'very_high', 'strong', 'moderate', or 'avoid'. Present for both legacy and predictive-framework sports. For predictive-framework sports it is null whenever `edge` is null — a tier ranks a bet against its price, so there is nothing to rank without an edge."""
    confidence_score: Optional[float]
    """Legacy points-engine confidence score, 0-1. A points fraction, not a calibrated probability. Legacy sports only — see `probability` for predictive-framework sports."""
    confidence_score_pre_validator: Optional[float]
    """Legacy confidence_score before the qualitative validator applied its delta. Legacy sports only."""
    coverage: Optional[float]
    """Legacy signal-coverage fraction, 0-1 — how many of the expected signal_* columns were populated for this bet. Legacy sports only — superseded by the continuous `sufficiency` for predictive-framework sports, which widens the interval instead of gating the response."""
    signals: Optional[Dict[str, Any]]
    """Legacy per-signal point breakdown (signal_research, signal_form, etc.); the same DB columns mean different things per sport — see `signals._labels` when present. Legacy sports only — superseded by `drivers` for predictive-framework sports."""
    validator: Optional[Dict[str, Any]]
    """Legacy qualitative-validator verdict: {stance, confidence, delta, validated_at}. Legacy sports only."""
    narrative: Optional[str]
    """Legacy per-bet narrative sentence generated alongside the validator pass. Legacy sports only."""
    rationale: List[str]
    """Legacy human-readable rationale bullets built from `signals`. Legacy sports only."""
    attribution: List[str]
    """Attribution keys backing `rationale`, in the same order. Legacy sports only."""
    probability: Optional[float]
    """Published probability for this outcome, 0-1. Equals `p_market` (the de-vigged market price) whenever `blend_w` is 0, which is the case for every league that does not yet have a fitted model that beat the market out-of-sample; otherwise it is the log-space blend of `p_model` and `p_market` at weight `blend_w`. Outcomes of the same market (e.g. ML_HOME + ML_DRAW + ML_AWAY) are blended jointly and sum to 1. Predictive-framework sports only."""
    interval: Optional[List[float]]
    """[lo, hi] band around `probability`, 0-1. Width is driven by `sufficiency`, so read it as 'how much evidence backs this number', not as a statistical confidence interval — the constants are calibrated against realised outcomes, not derived analytically. When `blend_w` is 0 the band reflects how mature and well-traded the quoted line is, so a freshly-opened, unmoved line gets a wider band than a heavily-traded one. Thin evidence widens this band rather than removing the response. Predictive-framework sports only."""
    p_model: Optional[float]
    """The fitted model's own probability for this outcome, before blending with the market. Null for any league that does not yet have a model cleared for publication — currently every soccer league. Predictive-framework sports only."""
    p_market: Optional[float]
    """De-vigged market probability for this outcome, before blending with the model. This is the bookmaker's price with the vig removed across the whole market, so the outcomes of a market sum to 1 — it is not recoverable from a single price by implied-probability arithmetic. Null when the fixture is unpriced. Predictive-framework sports only."""
    blend_w: Optional[float]
    """Weight given to `p_model` when blending it with `p_market` to produce `probability`, 0-1. 0 means the published probability is purely the de-vigged market. Weight is enabled per league and per bet token, and only where the model beat the market out-of-sample, so tokens on the same event can carry different weights. Predictive-framework sports only."""
    fair_price: Optional[int]
    """American-odds fair price implied by `probability` — the vig-free line. Comparing it to `market.price` gives the bookmaker's margin on this side. Predictive-framework sports only."""
    edge: Optional[float]
    """Expected profit per 1 unit staked at `market.price`, i.e. `probability x decimal_odds - 1`. Positive means the price pays more than the probability justifies. Null whenever `blend_w` is 0: a probability taken from the market has no honest edge against the price it came from, so reporting one would just be restating the vig. Predictive-framework sports only."""
    sufficiency: Optional[float]
    """How much evidence backs this assessment, 0-1, and the input that sets `interval` width and caps `tier`. Its inputs depend on what is actually being measured: while `blend_w` is 0 it measures the quoted line's maturity (movement count on the priced book/market and hours since that book's first quote), because there is no model sample to be thin about; once a model carries weight it reflects the model's own sample depth. Predictive-framework sports only."""
    phase: Optional[str]
    """'quant' when the assessment is purely deterministic (ratings, market, and model math). 'full' once a qualitative overlay — lineups, injuries, research alignment — is attached; `alignment` is populated only in that case. Predictive-framework sports only."""
    model_version: Optional[str]
    """Identifier of the parameter set that produced this assessment, so a published number can be traced to the version that made it. 'market_anchor' means no fitted model contributed. Per bet, since model weight is enabled per token. Predictive-framework sports only."""
    drivers: List[Dict[str, Any]]
    """Named, signed contributions to `probability` in probability units: {id, input, effect, direction, evidence}. `effect` is the shift in probability attributed to that factor and `direction` is 'up'/'down'/'neutral'. `evidence` is null for quantitative drivers (rating edge, HFA, rest) and, once populated, a list of `{fact_id, as_of}` citations into the Fact Ledger (`lumify_fixture_research`) for evidence-derived drivers — never an embedded quote/URL, which would duplicate that archive. Replaces `signals` for predictive-framework sports. Normally empty when no model contributed (`blend_w` 0); two exceptions carry `effect: 0` and never move probability: Stage 6 Match Context drivers (`soccer.match_context.*`, evidence-backed) and `soccer.cross_book_edge` (market-anchored price gap vs. the sharp consensus; `input` is the gap already published in `edges_by_book` — a line-shopping signal, not an expected-value claim). Predictive-framework sports only."""
    alignment: Optional[Dict[str, Any]]
    """Qualitative-overlay agreement detail. Populated only when `phase` is 'full'; null for every 'quant' assessment. Predictive-framework sports only."""
    fair: Optional[Dict[str, Any]]
    """Sharp-consensus fair price for this outcome: {probability, books, n_books, is_consensus}. `probability` is distinct from `p_market` (the *priced* book's own de-vigged probability) and from `fair_price` (American odds implied by the published `probability`, above) — it is the sharp-book reference (`SOCCER_SHARP_BOOKS`) that a cross-book edge is measured against. `is_consensus` is false whenever `n_books` < 2 — a single sharp book is a de-vig, not a consensus (true for every soccer row today: Pinnacle is the only soccer sharp book on our feed). Populated for MLS as of Stage 5 v1 (2026-07-29); null for every other league until its own book-independence screen and multi-book fetch are wired. Predictive-framework sports only."""
    edges_by_book: Optional[Dict[str, Any]]
    """Price gap versus the sharp-reference fair probability (`fair.probability`), keyed by bookmaker, for every independently-eligible soft book quoting this outcome — `fair.probability × decimal_odds − 1` at each book's posted price. This is a **price-gap / line-shopping metric**, not an expected-value recommendation: at the current N=2 soft-book coverage (FanDuel/Hard Rock on MLS), the measured winner's-curse component of a max-of-N pick is ~171% of the mean positive gap, and a closing-time backfill simulation of N=2 realized approximately −2.5% on the positive-gap population (see SOCCER_PROGRAM_PLAN.md §5.0 steps E / tenth pass). Rank soft books by these gaps for line-shopping (largest gap = furthest above the sharp reference); do not treat a positive gap as EV or as a bet recommendation, and do not badge picks as '+EV'. Populated for MLS as of Stage 5 v1; null for every other league until its own gate and fetch are wired, and null for any market with no eligible soft book quoting it. Predictive-framework sports only."""
    best: Optional[Dict[str, Any]]
    """Highest price-gap pick across `edges_by_book`: {book, price, edge, quote_age_seconds}. `edge` is the field's raw maximum (`shrinkage=0.0` — winner's-curse correction closed as won't-fit at N=2). Same caveats as `edges_by_book`: this is a price gap versus a de-vigged sharp reference, **not** an expected-value claim; at N=2 the winner's-curse magnitude is ~171% of the mean positive gap and a closing-time N=2 backfill simulation realized ≈−2.5% on positive-gap picks. Use `best.book`/`best.price` as the line-shopping target for this outcome; do not read `best.edge` as EV or as a bet recommendation. `quote_age_seconds` is `best.book`'s posted-price age at publish time — a stale soft-book price is excluded before selection (30-minute freshness threshold). Populated for MLS as of Stage 5 v1 (2026-07-29); null for every other league or whenever `edges_by_book` is empty. Predictive-framework sports only."""


class CreditPack(TypedDict, total=False):
    id: Optional[int]
    name: Optional[str]
    credits: Optional[int]
    price_cents: Optional[int]
    bonus_credits: Optional[int]


class CreditPackListResponse(TypedDict, total=False):
    data: List[CreditPack]
    total: int


class CreditTopupResponse(TypedDict, total=False):
    success: Optional[bool]
    credits_added: Optional[int]
    bonus_credits: Optional[int]
    pack_id: Optional[int]


class EstimateCall(TypedDict, total=False):
    tool: str
    """The MCP tool / SDK call to estimate, e.g. 'get_event', 'batch_get_events', 'get_odds'. See GET /v1/estimate/tools for the full supported list."""
    arguments: Dict[str, Any]
    """Same arguments you'd pass to that tool/endpoint, e.g. {"event_id": 123, "include_odds": true}."""


class EstimateRequest(TypedDict, total=False):
    calls: List[EstimateCall]
    """One or more planned calls to estimate in a single round-trip."""


class EstimateResponse(TypedDict, total=False):
    estimates: List[EstimateResult]
    total_min_credits: int
    total_max_credits: int


class EstimateResult(TypedDict, total=False):
    tool: str
    min_credits: int
    """Cheapest realistic outcome (e.g. requested data not yet available)."""
    max_credits: int
    """Priciest realistic outcome (e.g. all requested data is available)."""
    note: Optional[str]
    """Why the cost varies, when it does."""


class EventDetail(TypedDict, total=False):
    id: int
    name: Optional[str]
    sport: Optional[str]
    league: Optional[str]
    season_id: Optional[int]
    starts_at: Optional[str]
    """ISO-8601 UTC start time."""
    status: Optional[str]
    period: Optional[str]
    clock: Optional[str]
    venue: Optional[Dict[str, Any]]
    participants: List[Participant]
    updated_at: Optional[str]


class EventListResponse(TypedDict, total=False):
    events: List[EventSummary]
    total: int
    next_after_id: Optional[int]


class EventSummary(TypedDict, total=False):
    id: int
    name: Optional[str]
    sport: Optional[str]
    league: Optional[str]
    season_id: Optional[int]
    starts_at: Optional[str]
    """ISO-8601 UTC start time."""
    status: Optional[str]
    period: Optional[str]
    clock: Optional[str]
    venue: Optional[Dict[str, Any]]


class HTTPValidationError(TypedDict, total=False):
    detail: List[ValidationError]


class IntelligenceResponse(TypedDict, total=False):
    event_id: Optional[int]
    """Lumify event ID this intelligence describes. Present on the standalone endpoint; omitted when inlined under an event via include_intelligence."""
    available: bool
    """False when no intelligence has been computed for this event yet — every other field is then null/empty and the request is not charged."""
    odds_source: Optional[str]
    """Bookmaker `bets[].market` prices were sourced from. For predictive-framework sports this is the assessment's market_book (not a live `?bookmaker=` overlay). For legacy sports it follows the system default or `?bookmaker=` when that override is used."""
    sport: Optional[str]
    """Sport slug for this event."""
    league: Optional[str]
    """League slug for this event, if any."""
    players: Dict[str, Any]
    """Home/away (or p1/p2) participant identification, keyed by role: {role: {name, player_id, team_id}}."""
    has_recommend: Optional[bool]
    """True when at least one bet meets the recommendation threshold; false when none do; null when intelligence has not been computed for this event. For predictive-framework sports a recommendation requires an `edge`, so this is false for any event whose bets are all market-anchored (`blend_w` 0)."""
    analyst_take: Optional[str]
    """Short natural-language read on the event as a whole (as opposed to a single bet). Null when no narrative has been generated."""
    match_overview: Optional[str]
    """Longer natural-language preview of the matchup — form, context, and what to watch. Null when no narrative has been generated."""
    intelligence_updated_at: Optional[str]
    """ISO-8601 UTC timestamp of the most recent change anywhere in this payload — the maximum of the per-bet `computed_at` values for predictive-framework sports. Because individual markets are only rewritten when they move, use the per-bet `computed_at` to reason about a specific bet rather than this event-level maximum."""
    bets: List[BetIntelligence]
    """One entry per priced bet token. Which fields are populated depends on whether the sport/league is on the predictive framework (probability/edge fields) or the legacy points engine (confidence_score/signals fields) — see BetIntelligence. Outcomes of the same market sum to 1 for predictive-framework sports."""
    matchup: Optional[Dict[str, Any]]
    """MLB-only probable-starter context (home_starter/away_starter with name/hand/era/confirmed), extracted from research context. Absent for every other sport."""


class LeagueSummary(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    name: Optional[str]
    abbreviation: Optional[str]
    league_type: Optional[str]
    country_code: Optional[str]
    current_season: Optional[SeasonSummary]


class MlbStatsHeadToHead(TypedDict, total=False):
    window: int
    """Max trailing meetings considered (see `windows.head_to_head`)."""
    meetings: List[MlbStatsHeadToHeadMeeting]
    """Most-recent-first past meetings between these two teams, up to `window`."""
    total: int
    """Number of meetings returned in `meetings`."""


class MlbStatsHeadToHeadMeeting(TypedDict, total=False):
    home_runs: Optional[int]
    """Runs scored by this event's home team in that past meeting."""
    away_runs: Optional[int]
    """Runs scored by this event's away team in that past meeting."""


class MlbStatsLineup(TypedDict, total=False):
    available: bool
    """False when no lineup has been ingested yet for this side."""
    batting_order: List[MlbStatsLineupPlayer]
    """The 9 starting batters, ordered by `batting_order` (1-9)."""
    starting_pitcher: Optional[MlbStatsLineupPlayer]
    """This side's starting pitcher. Null when unavailable."""
    bench: List[MlbStatsLineupPlayer]
    """Players who entered the game but weren't in the starting lineup (pinch hitters, relievers, defensive subs)."""
    captured_at: Optional[str]
    """When this lineup was captured from the source, 'YYYY-MM-DD HH:MM:SS'."""


class MlbStatsLineupPlayer(TypedDict, total=False):
    name: Optional[str]
    position: Optional[str]
    """Position abbreviation, e.g. '1B', 'SS', 'P'."""
    player_id: Optional[int]
    """Lumify player ID."""
    role: Optional[str]
    """'batter' or 'pitcher'."""
    batting_order: Optional[int]
    """Batting order slot (1-9) for starters with role='batter'. Null for pitchers and subs."""
    starter: bool
    """True in `batting_order`/`starting_pitcher`, false in `bench`."""


class MlbStatsRatesBlock(TypedDict, total=False):
    source: Optional[str]
    """Provenance tag, e.g. 'player_game_stats_sum' (own box scores, summed to team level)."""
    window: Optional[str]
    """Which rolling window this block covers: 'l5' (see `window_size` for the fixed game count) or 'season' (an intentionally variable-length window — see `games` for how many games it actually covers for this team)."""
    window_size: Optional[int]
    """Fixed sample depth for this window, only present when the window has one (e.g. 5 for 'l5'). Omitted for 'season' — use `games` instead."""
    games: int
    """Games with box-score data included in this aggregate."""
    at_bats: Optional[float]
    """Avg. team at-bats per game."""
    hits: Optional[float]
    """Avg. team hits per game."""
    runs: Optional[float]
    """Avg. team runs scored per game."""
    home_runs: Optional[float]
    """Avg. team home runs per game."""
    walks: Optional[float]
    """Avg. team walks (bases on balls) drawn per game."""
    strikeouts: Optional[float]
    """Avg. team batter strikeouts per game."""
    doubles: Optional[float]
    """Avg. team doubles per game."""
    stolen_bases: Optional[float]
    """Avg. team stolen bases per game."""
    batting_avg: Optional[float]
    """Team batting average across the window: total hits / total at-bats (not an average of per-game averages)."""
    outs: Optional[float]
    """Avg. team outs recorded per game. The additive unit behind innings_pitched/ERA/WHIP/K9/BB9."""
    innings_pitched: Optional[float]
    """Avg. team innings pitched per game as true innings (total outs ÷ 3 ÷ games). Not baseball notation — see starting_pitcher.innings_pitched for N.outs display."""
    earned_runs: Optional[float]
    """Avg. team earned runs allowed per game."""
    hits_allowed: Optional[float]
    """Avg. team hits allowed per game."""
    walks_allowed: Optional[float]
    """Avg. team walks allowed per game."""
    strikeouts_pitched: Optional[float]
    """Avg. team pitcher strikeouts recorded per game."""
    home_runs_allowed: Optional[float]
    """Avg. team home runs allowed per game."""
    era: Optional[float]
    """Team ERA across the window: (total earned runs × 9) / (total outs ÷ 3). Uses outs math — baseball IP notation (.1/.2 = outs) is not additive."""
    whip: Optional[float]
    """Team WHIP across the window: (total walks allowed + total hits allowed) / (total outs ÷ 3)."""
    k9: Optional[float]
    """Team strikeouts per 9 innings across the window: (total pitcher strikeouts × 9) / (total outs ÷ 3)."""
    bb9: Optional[float]
    """Team walks allowed per 9 innings across the window: (total walks allowed × 9) / (total outs ÷ 3)."""
    field_games: Dict[str, Any]
    """Per-field sample size, keyed by the raw box-score slugs summed into the fields above (at_bats, hits, runs, home_runs, walks, strikeouts, doubles, stolen_bases, outs, innings_pitched, earned_runs, hits_allowed, walks_allowed, strikeouts_pitched, home_runs_allowed). `games` is how many games are in this window overall, but an individual field can have a smaller count when a box score omits that stat."""


class MlbStatsRecentForm(TypedDict, total=False):
    window: int
    """Number of trailing completed games this form line covers."""
    results: List[str]
    """Most-recent-first results over `window`: 'W' or 'L' (no ties in MLB)."""
    runs_scored: List[int]
    """Runs this team scored in each game, same order as `results`."""
    runs_allowed: List[int]
    """Runs this team allowed in each game, same order as `results`."""


class MlbStatsRecord(TypedDict, total=False):
    source: Optional[str]
    """Provenance tag, e.g. 'season_to_date'."""
    wins: int
    """Season-to-date wins."""
    losses: int
    """Season-to-date losses."""
    games: int
    """Season-to-date completed games."""
    win_pct: Optional[float]
    """wins / games. Null with zero games."""
    runs_for: int
    """Total runs scored this season to date."""
    runs_against: int
    """Total runs allowed this season to date."""
    run_differential: int
    """runs_for - runs_against."""


class MlbStatsResponse(TypedDict, total=False):
    event_id: int
    """Lumify event ID."""
    available: bool
    """False when either team hasn't resolved for this fixture yet — every other field is omitted in that case and the call isn't billed."""
    league_slug: Optional[str]
    """League slug — always 'mlb'."""
    windows: Optional[MlbStatsWindows]
    teams: Optional[MlbStatsTeams]
    head_to_head: Optional[MlbStatsHeadToHead]


class MlbStatsStartingPitcher(TypedDict, total=False):
    available: bool
    """False when no starting pitcher has been identified for this side yet (lineup not ingested)."""
    player_id: Optional[int]
    """Lumify player ID."""
    name: Optional[str]
    position: Optional[str]
    """Position abbreviation from the lineup (typically 'P'; may be 'DH' etc. for two-way players)."""
    games_started: int
    """Season-to-date games started (boxscore gamesStarted=1 only — relief appearances do not count)."""
    innings_pitched: Optional[float]
    """Season-to-date total innings pitched in baseball notation (e.g. 128.1 = 128⅔), derived from summed outs."""
    era: Optional[float]
    """Season-to-date ERA: (total earned runs × 9) / (total outs ÷ 3) — derived from our own box scores, not a live vendor fetch."""
    whip: Optional[float]
    """Season-to-date WHIP: (total walks allowed + total hits allowed) / (total outs ÷ 3)."""
    k9: Optional[float]
    """Season-to-date strikeouts per 9 innings (outs-based denominator)."""
    bb9: Optional[float]
    """Season-to-date walks allowed per 9 innings (outs-based denominator)."""


class MlbStatsTeam(TypedDict, total=False):
    team_id: Optional[int]
    name: Optional[str]
    abbreviation: Optional[str]
    rest_days: Optional[int]
    """Days since this team's previous completed game."""
    recent_form: Optional[MlbStatsRecentForm]
    record: Optional[MlbStatsRecord]
    """Season-to-date W/L record and run differential."""
    rates_l5: Optional[MlbStatsRatesBlock]
    """Team batting/pitching rate aggregates over the trailing 5 games."""
    rates_season: Optional[MlbStatsRatesBlock]
    """Team batting/pitching rate aggregates over the current season."""
    starting_pitcher: Optional[MlbStatsStartingPitcher]
    """This side's starting pitcher for this game, with his own season rate stats."""
    lineup: Optional[MlbStatsLineup]


class MlbStatsTeams(TypedDict, total=False):
    home: Optional[MlbStatsTeam]
    away: Optional[MlbStatsTeam]


class MlbStatsWindows(TypedDict, total=False):
    recent_form: int
    """Trailing games covered by each team's `recent_form`."""
    rates_l5: int
    """Trailing games covered by each team's `rates_l5`."""
    rates_season: str
    """Always the literal string 'season' — a deliberately variable-length window (see each team's `rates_season.games`), unlike the fixed integer windows above."""
    head_to_head: int
    """Trailing meetings between these two teams considered for `head_to_head`."""


NLQueryFilters = TypedDict(
    'NLQueryFilters',
    {
        'sport': Optional[str],
        'status': Optional[str],
        'date': Optional[str],
        'from': Optional[str],
        'to': Optional[str],
        'limit': Optional[int],
    },
    total=False,
)


class NLQueryRequest(TypedDict, total=False):
    query: str
    """Free text, e.g. 'live nfl games today' or 'college basketball this week'."""
    limit: Optional[int]
    """Overrides any limit parsed from the query text. Max 100."""


class NLQueryResponse(TypedDict, total=False):
    query: str
    """The original natural-language query text."""
    interpreted: NLQueryFilters
    """The GET /v1/events filters parsed from the query text."""
    unrecognized_terms: List[str]
    """Query words that didn't map to a known filter."""
    equivalent_request: str
    """The literal GET /v1/events request this query was translated to."""
    events: List[EventSummary]
    total: int
    next_after_id: Optional[int]


class OddsHistoryResponse(TypedDict, total=False):
    event_id: int
    movements: List[Dict[str, Any]]
    total: int


class OddsResponse(TypedDict, total=False):
    event_id: Optional[int]
    available: bool
    bookmakers: List[Dict[str, Any]]
    last_updated: Optional[str]


class Participant(TypedDict, total=False):
    participant_id: Optional[int]
    role: Optional[str]
    team: Optional[Dict[str, Any]]
    player: Optional[Dict[str, Any]]
    score: Optional[str]
    is_winner: Optional[bool]


class Player(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    full_name: Optional[str]
    first_name: Optional[str]
    last_name: Optional[str]
    sport: Optional[str]
    country_code: Optional[str]
    birthdate: Optional[str]
    """YYYY-MM-DD date of birth."""
    position: Optional[str]
    handedness: Optional[str]
    height_cm: Optional[int]
    weight_kg: Optional[float]
    tennis_ranking: Optional[int]
    tennis_ranking_points: Optional[int]
    current_team_id: Optional[int]
    current_team_name: Optional[str]
    is_active: Optional[bool]
    retired_at: Optional[str]
    image_url: Optional[str]


class PlayerEventsResponse(TypedDict, total=False):
    player_id: int
    data: List[Dict[str, Any]]
    has_more: bool
    next_after_id: Optional[int]


class PlayersListResponse(TypedDict, total=False):
    data: List[Player]
    has_more: bool
    next_after_id: Optional[int]


class ScoreEntry(TypedDict, total=False):
    role: Optional[str]
    name: Optional[str]
    abbreviation: Optional[str]
    score: Optional[str]
    is_winner: Optional[bool]
    period_scores: List[Dict[str, Any]]


class ScoreResponse(TypedDict, total=False):
    event_id: int
    status: Optional[str]
    finished: Optional[bool]
    period: Optional[str]
    clock: Optional[str]
    scores: List[ScoreEntry]
    updated_at: Optional[str]


class Season(TypedDict, total=False):
    id: Optional[int]
    year: Optional[int]
    name: Optional[str]
    phase: Optional[str]
    start_date: Optional[str]
    end_date: Optional[str]
    is_current: Optional[bool]
    sport: Optional[Dict[str, Any]]
    league: Optional[Dict[str, Any]]


class SeasonSummary(TypedDict, total=False):
    id: Optional[int]
    year: Optional[int]
    name: Optional[str]
    phase: Optional[str]
    start_date: Optional[str]
    end_date: Optional[str]


class SeasonsListResponse(TypedDict, total=False):
    seasons: List[Season]
    total: int


class SplitsResponse(TypedDict, total=False):
    event_id: int
    available: bool
    captured_at: Optional[str]
    consensus: Dict[str, Any]
    books: List[Dict[str, Any]]


class Sport(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    name: Optional[str]
    is_team_sport: Optional[bool]
    leagues: List[LeagueSummary]


class SportsListResponse(TypedDict, total=False):
    sports: List[Sport]
    total: int


class StatsHeadToHead(TypedDict, total=False):
    window: int
    """Max trailing meetings considered (see `windows.head_to_head`)."""
    meetings: List[StatsHeadToHeadMeeting]
    """Most-recent-first past meetings between these two teams, up to `window`."""
    total: int
    """Number of meetings returned in `meetings`."""


class StatsHeadToHeadMeeting(TypedDict, total=False):
    home_goals: Optional[int]
    """Goals scored by this event's home team in that past meeting."""
    away_goals: Optional[int]
    """Goals scored by this event's away team in that past meeting."""


class StatsLeagueContext(TypedDict, total=False):
    avg_goals_per_team: Optional[float]
    """League-wide average goals scored per team per game this season, used as the baseline the /intelligence layer compares each team's attack/defense against. Null for competitions that use a fixed baseline instead (e.g. World Cup)."""


class StatsLineup(TypedDict, total=False):
    available: bool
    """False when no lineup has been ingested yet for this side."""
    formation: Optional[str]
    """e.g. '4-3-3'. Null when unavailable."""
    starters: List[StatsLineupPlayer]
    bench: List[StatsLineupPlayer]
    captured_at: Optional[str]
    """When this lineup was captured from the source, 'YYYY-MM-DD HH:MM:SS'."""


class StatsLineupPlayer(TypedDict, total=False):
    name: Optional[str]
    position: Optional[str]
    """Position abbreviation, e.g. 'GK', 'CB'."""
    jersey: Optional[str]
    formation_place: Optional[int]
    """Slot index within the formation, when ESPN provides one."""
    espn_athlete_id: Optional[str]
    starter: bool
    """True in `starters`, false in `bench`."""


class StatsRatesBlock(TypedDict, total=False):
    source: Optional[str]
    """Provenance tag, e.g. 'event_stats_avg' (ESPN box-score averages)."""
    window: Optional[Union[str, int]]
    """Which rolling window this block covers: 'l5' (see `window_size` for the fixed game count) or 'season' (an intentionally variable-length window — see `games` for how many games it actually covers for this team)."""
    window_size: Optional[int]
    """Fixed sample depth for this window, only present when the window has one (e.g. 5 for 'l5'). Omitted for 'season', since season length varies by team — use `games` instead."""
    games: int
    """Games with box-score data included in this average."""
    shots_for: Optional[float]
    """Avg. shots taken per game."""
    shots_against: Optional[float]
    """Avg. shots conceded per game."""
    shots_on_target_for: Optional[float]
    """Avg. shots on target taken per game."""
    shots_on_target_against: Optional[float]
    """Avg. shots on target conceded per game."""
    possession_pct: Optional[float]
    """Avg. possession percentage (0-100)."""
    corners_for: Optional[float]
    """Avg. corners won per game."""
    corners_against: Optional[float]
    """Avg. corners conceded per game."""
    fouls: Optional[float]
    """Avg. fouls committed per game."""
    yellow_cards: Optional[float]
    """Avg. yellow cards received per game."""
    red_cards: Optional[float]
    """Avg. red cards received per game."""
    passes: Optional[float]
    """Avg. total passes per game (ESPN totalPasses; see pass_accuracy_pct for completion rate)."""
    pass_accuracy_pct: Optional[float]
    """Avg. pass completion percentage (0-100)."""
    saves: Optional[float]
    """Avg. goalkeeper saves per game."""
    save_rate: Optional[float]
    """Saves / shots on target faced across the window (not an average of per-game rates)."""
    field_games: Dict[str, Any]
    """Per-field sample size, keyed by the metric names above. `games` is how many games are in this window overall, but an individual field can have a smaller count when a source's box score omits that stat for some fixtures — lets agents tell 'averaged over all N games' apart from 'averaged over fewer'."""


class StatsRecentForm(TypedDict, total=False):
    window: int
    """Number of trailing completed games this form line covers."""
    results: List[str]
    """Most-recent-first results over `window`: 'W', 'D', or 'L'."""
    goals_scored: List[int]
    """Goals this team scored in each game, same order as `results`."""
    goals_conceded: List[int]
    """Goals this team conceded in each game, same order as `results`."""


class StatsResponse(TypedDict, total=False):
    event_id: int
    """Lumify event ID."""
    available: bool
    """False when either team hasn't resolved for this fixture yet — every other field is omitted in that case and the call isn't billed."""
    league_slug: Optional[str]
    """League slug, e.g. 'mls'."""
    profile: Optional[str]
    """'club' or 'world_cup'. Determines the shape of `teams.*.team_strength`, `teams.*.venue`, and whether `teams.*.sos` is populated."""
    neutral_site: Optional[bool]
    """Whether this fixture is at a neutral venue. Informational here — not used in any of this endpoint's own aggregates, but factored into home-advantage scoring on GET /v1/events/{id}/intelligence."""
    windows: Optional[StatsWindows]
    teams: Optional[StatsTeams]
    head_to_head: Optional[StatsHeadToHead]
    league_context: Optional[StatsLeagueContext]


class StatsSos(TypedDict, total=False):
    source: Optional[str]
    """Provenance tag, e.g. 'opp_ppg_avg'."""
    window: int
    """Number of trailing opponents this strength-of-schedule average covers."""
    games: int
    """Opponent games actually available within `window`."""
    avg_opp_ppg: Optional[float]
    """Average points-per-game of the opponents faced in `window`."""
    avg_opp_rank: Optional[float]
    """Average league-table rank of the opponents faced in `window`."""


class StatsTeam(TypedDict, total=False):
    team_id: Optional[int]
    name: Optional[str]
    abbreviation: Optional[str]
    rest_days: Optional[int]
    """Days since this team's previous completed game."""
    recent_form: Optional[StatsRecentForm]
    rates_l5: Optional[StatsRatesBlock]
    """Boxscore rate averages over the trailing 5 games."""
    rates_season: Optional[StatsRatesBlock]
    """Boxscore rate averages over the current season/edition."""
    lineup: Optional[StatsLineup]
    team_strength: Optional[Dict[str, Any]]
    """Club fixtures: {source: 'league_table_ppg', ppg, games, points, w, d, l, gf, ga, gd, rank} from the current league table. World Cup fixtures: {source: 'fifa_rank', fifa_rank} since there's no in-tournament table yet."""
    venue: Optional[Dict[str, Any]]
    """Club fixtures: {source: 'home_away_ppg_split', home_ppg, home_games, away_ppg, away_games}. World Cup fixtures: {source: 'confederation', confederation}, since home/away splits don't apply at a neutral-site tournament."""
    sos: Optional[StatsSos]
    """Strength of schedule (avg. opponent PPG/rank over recent games). Null for World Cup fixtures — there's no league table to compute it from."""


class StatsTeams(TypedDict, total=False):
    home: Optional[StatsTeam]
    away: Optional[StatsTeam]


class StatsWindows(TypedDict, total=False):
    recent_form: int
    """Trailing games covered by each team's `recent_form`."""
    rates_l5: int
    """Trailing games covered by each team's `rates_l5`."""
    rates_season: Union[str, int]
    """Always the literal string 'season' — a deliberately variable-length window (see each team's `rates_season.games`), unlike the fixed integer windows above."""
    head_to_head: int
    """Trailing meetings between these two teams considered for `head_to_head`."""
    sos: int
    """Trailing opponents covered by each team's `sos`."""


class Team(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    name: Optional[str]
    short_name: Optional[str]
    abbreviation: Optional[str]
    sport: Optional[str]
    league: Optional[str]
    city: Optional[str]
    state: Optional[str]
    country_code: Optional[str]
    conference: Optional[str]
    division: Optional[str]
    venue: Optional[Dict[str, Any]]
    is_active: Optional[bool]


class TeamsListResponse(TypedDict, total=False):
    data: List[Team]
    has_more: bool
    next_after_id: Optional[int]


TrialKeyRequest = TypedDict(
    'TrialKeyRequest',
    {
        'cf-turnstile-response': str,
    },
    total=False,
)


class ValidationError(TypedDict, total=False):
    loc: List[Union[str, int]]
    msg: str
    type: str
    input: Any
    ctx: Dict[str, Any]


class WebhookCreateResponse(TypedDict, total=False):
    id: Optional[int]
    url: Optional[str]
    event_types: List[str]
    sport: Optional[str]
    event_id: Optional[int]
    is_active: Optional[bool]
    created_at: Optional[str]
    signing_secret: Optional[str]
    """Returned only on create — store it to verify Lumify-Signature."""


class WebhookDeleteResponse(TypedDict, total=False):
    deleted: bool
    id: Optional[int]


class WebhookDeliveryItem(TypedDict, total=False):
    id: Optional[int]
    event_type: Optional[str]
    event_id: Optional[int]
    attempt: Optional[int]
    parent_delivery_id: Optional[int]
    status_code: Optional[int]
    success: Optional[bool]
    error: Optional[str]
    given_up: Optional[bool]
    next_retry_at: Optional[str]
    delivered_at: Optional[str]


class WebhookDeliveryListResponse(TypedDict, total=False):
    data: List[WebhookDeliveryItem]
    next_after_id: Optional[int]


class WebhookListResponse(TypedDict, total=False):
    data: List[WebhookSubscription]
    total: int


class WebhookSubscription(TypedDict, total=False):
    id: Optional[int]
    url: Optional[str]
    event_types: List[str]
    sport: Optional[str]
    event_id: Optional[int]
    is_active: Optional[bool]
    created_at: Optional[str]
    signing_secret: Optional[str]
    """Returned only on create — store it to verify Lumify-Signature."""
