# AUTO-GENERATED by scripts/gen_models.py from the shared OpenAPI slice
# clients/lumify-sdk/openapi/openapi.sdk.json (produced by
# scripts/export_openapi_sdk.py at the repo root). Do not edit by hand —
# run `python scripts/gen_models.py` after regenerating the schema.
#
# This is the SDK's data-model layer (sync gate G2): every TypedDict here
# maps 1:1 to a component schema in the live OpenAPI contract — the SAME
# artifact the TypeScript SDK generates from — so response shapes can never
# silently drift from the API or between the two SDKs.

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

try:  # TypedDict is in typing on 3.8+, but this keeps intent explicit.
    from typing import TypedDict
except ImportError:  # pragma: no cover - Python < 3.8 unsupported
    from typing_extensions import TypedDict  # type: ignore


__all__ = [
    "AgentApiKey",
    "AgentApiKeyListResponse",
    "AgentApiKeyRevokeResponse",
    "AgentCreditsResponse",
    "BatchEventsRequest",
    "BatchEventsResponse",
    "BetIntelligence",
    "CreditPack",
    "CreditPackListResponse",
    "CreditTopupResponse",
    "EstimateCall",
    "EstimateRequest",
    "EstimateResponse",
    "EstimateResult",
    "EventDetail",
    "EventListResponse",
    "EventSummary",
    "HTTPValidationError",
    "IntelligenceResponse",
    "LeagueSummary",
    "NLQueryFilters",
    "NLQueryRequest",
    "NLQueryResponse",
    "OddsHistoryResponse",
    "OddsResponse",
    "Participant",
    "Player",
    "PlayerEventsResponse",
    "PlayersListResponse",
    "ScoreEntry",
    "ScoreResponse",
    "Season",
    "SeasonSummary",
    "SeasonsListResponse",
    "SplitsResponse",
    "Sport",
    "SportsListResponse",
    "Team",
    "TeamsListResponse",
    "TrialKeyRequest",
    "ValidationError",
    "WebhookCreateResponse",
    "WebhookDeleteResponse",
    "WebhookDeliveryItem",
    "WebhookDeliveryListResponse",
    "WebhookListResponse",
    "WebhookSubscription",
]


class AgentApiKey(TypedDict, total=False):
    id: Optional[int]
    name: Optional[str]
    key_prefix: Optional[str]
    scopes: Optional[List[str]]
    created_at: Optional[str]
    last_used_at: Optional[str]
    expires_at: Optional[str]
    is_active: Optional[bool]
    key: Optional[str]
    """Full API key — returned once on create."""


class AgentApiKeyListResponse(TypedDict, total=False):
    data: List[AgentApiKey]
    total: int


class AgentApiKeyRevokeResponse(TypedDict, total=False):
    revoked: bool
    id: Optional[int]


class AgentCreditsResponse(TypedDict, total=False):
    tier: Optional[str]
    credits_used: Optional[int]
    credit_limit: Optional[int]
    bonus_credits: Optional[int]
    total_remaining: Optional[int]
    period_start: Optional[str]
    period_end: Optional[str]
    is_trial: Optional[bool]
    is_trial_expired: Optional[bool]


class BatchEventsRequest(TypedDict, total=False):
    event_ids: List[int]
    """Event ids to fetch (max 25). Duplicates are billed once."""
    include_odds: bool
    """Inline current odds on each event (+1 credit per event when available)."""
    include_intelligence: bool
    """Inline bet intelligence on each event (+1 credit per event when available)."""
    bookmaker: Optional[str]
    """Bookmaker for inlined odds; defaults to pinnacle, 'all' for every book."""


class BatchEventsResponse(TypedDict, total=False):
    events: List[EventDetail]
    not_found: List[int]
    """Requested event_ids that don't exist. Never billed."""
    total: int


class BetIntelligence(TypedDict, total=False):
    bet_type: Optional[str]
    tier: Optional[str]
    confidence_score: Optional[float]
    coverage: Optional[float]
    market: Optional[Dict[str, Any]]
    signals: Optional[Dict[str, Any]]
    validator: Optional[Dict[str, Any]]
    narrative: Optional[str]
    rationale: List[str]
    attribution: List[str]


class CreditPack(TypedDict, total=False):
    id: Optional[int]
    name: Optional[str]
    credits: Optional[int]
    price_cents: Optional[int]
    bonus_credits: Optional[int]


class CreditPackListResponse(TypedDict, total=False):
    data: List[CreditPack]
    total: int


class CreditTopupResponse(TypedDict, total=False):
    success: Optional[bool]
    credits_added: Optional[int]
    bonus_credits: Optional[int]
    pack_id: Optional[int]


class EstimateCall(TypedDict, total=False):
    tool: str
    """The MCP tool / SDK call to estimate, e.g. 'get_event', 'batch_get_events', 'get_odds'. See GET /v1/estimate/tools for the full supported list."""
    arguments: Dict[str, Any]
    """Same arguments you'd pass to that tool/endpoint, e.g. {"event_id": 123, "include_odds": true}."""


class EstimateRequest(TypedDict, total=False):
    calls: List[EstimateCall]
    """One or more planned calls to estimate in a single round-trip."""


class EstimateResponse(TypedDict, total=False):
    estimates: List[EstimateResult]
    total_min_credits: int
    total_max_credits: int


class EstimateResult(TypedDict, total=False):
    tool: str
    min_credits: int
    """Cheapest realistic outcome (e.g. requested data not yet available)."""
    max_credits: int
    """Priciest realistic outcome (e.g. all requested data is available)."""
    note: Optional[str]
    """Why the cost varies, when it does."""


class EventDetail(TypedDict, total=False):
    id: int
    name: Optional[str]
    sport: Optional[str]
    league: Optional[str]
    season_id: Optional[int]
    starts_at: Optional[str]
    """ISO-8601 UTC start time."""
    status: Optional[str]
    period: Optional[str]
    clock: Optional[str]
    venue: Optional[Dict[str, Any]]
    participants: List[Participant]
    updated_at: Optional[str]


class EventListResponse(TypedDict, total=False):
    events: List[EventSummary]
    total: int
    next_after_id: Optional[int]


class EventSummary(TypedDict, total=False):
    id: int
    name: Optional[str]
    sport: Optional[str]
    league: Optional[str]
    season_id: Optional[int]
    starts_at: Optional[str]
    """ISO-8601 UTC start time."""
    status: Optional[str]
    period: Optional[str]
    clock: Optional[str]
    venue: Optional[Dict[str, Any]]


class HTTPValidationError(TypedDict, total=False):
    detail: List[ValidationError]


class IntelligenceResponse(TypedDict, total=False):
    event_id: Optional[int]
    available: bool
    has_recommend: Optional[bool]
    analyst_take: Optional[str]
    match_overview: Optional[str]
    intelligence_updated_at: Optional[str]
    bets: List[BetIntelligence]


class LeagueSummary(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    name: Optional[str]
    abbreviation: Optional[str]
    league_type: Optional[str]
    country_code: Optional[str]
    current_season: Optional[SeasonSummary]


NLQueryFilters = TypedDict(
    'NLQueryFilters',
    {
        'sport': Optional[str],
        'status': Optional[str],
        'date': Optional[str],
        'from': Optional[str],
        'to': Optional[str],
        'limit': Optional[int],
    },
    total=False,
)


class NLQueryRequest(TypedDict, total=False):
    query: str
    """Free text, e.g. 'live nfl games today' or 'college basketball this week'."""
    limit: Optional[int]
    """Overrides any limit parsed from the query text. Max 100."""


class NLQueryResponse(TypedDict, total=False):
    query: str
    """The original natural-language query text."""
    interpreted: NLQueryFilters
    """The GET /v1/events filters parsed from the query text."""
    unrecognized_terms: List[str]
    """Query words that didn't map to a known filter."""
    equivalent_request: str
    """The literal GET /v1/events request this query was translated to."""
    events: List[EventSummary]
    total: int
    next_after_id: Optional[int]


class OddsHistoryResponse(TypedDict, total=False):
    event_id: int
    movements: List[Dict[str, Any]]
    total: int


class OddsResponse(TypedDict, total=False):
    event_id: Optional[int]
    available: bool
    bookmakers: List[Dict[str, Any]]
    last_updated: Optional[str]


class Participant(TypedDict, total=False):
    participant_id: Optional[int]
    role: Optional[str]
    team: Optional[Dict[str, Any]]
    player: Optional[Dict[str, Any]]
    score: Optional[str]
    is_winner: Optional[bool]


class Player(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    full_name: Optional[str]
    first_name: Optional[str]
    last_name: Optional[str]
    sport: Optional[str]
    country_code: Optional[str]
    birthdate: Optional[str]
    """YYYY-MM-DD date of birth."""
    position: Optional[str]
    handedness: Optional[str]
    height_cm: Optional[int]
    weight_kg: Optional[float]
    tennis_ranking: Optional[int]
    tennis_ranking_points: Optional[int]
    current_team_id: Optional[int]
    current_team_name: Optional[str]
    is_active: Optional[bool]
    retired_at: Optional[str]
    image_url: Optional[str]


class PlayerEventsResponse(TypedDict, total=False):
    player_id: int
    data: List[Dict[str, Any]]
    has_more: bool
    next_after_id: Optional[int]


class PlayersListResponse(TypedDict, total=False):
    data: List[Player]
    has_more: bool
    next_after_id: Optional[int]


class ScoreEntry(TypedDict, total=False):
    role: Optional[str]
    name: Optional[str]
    abbreviation: Optional[str]
    score: Optional[str]
    is_winner: Optional[bool]
    period_scores: List[Dict[str, Any]]


class ScoreResponse(TypedDict, total=False):
    event_id: int
    status: Optional[str]
    finished: Optional[bool]
    period: Optional[str]
    clock: Optional[str]
    scores: List[ScoreEntry]
    updated_at: Optional[str]


class Season(TypedDict, total=False):
    id: Optional[int]
    year: Optional[int]
    name: Optional[str]
    phase: Optional[str]
    start_date: Optional[str]
    end_date: Optional[str]
    is_current: Optional[bool]
    sport: Optional[Dict[str, Any]]
    league: Optional[Dict[str, Any]]


class SeasonSummary(TypedDict, total=False):
    id: Optional[int]
    year: Optional[int]
    name: Optional[str]
    phase: Optional[str]
    start_date: Optional[str]
    end_date: Optional[str]


class SeasonsListResponse(TypedDict, total=False):
    seasons: List[Season]
    total: int


class SplitsResponse(TypedDict, total=False):
    event_id: int
    available: bool
    captured_at: Optional[str]
    consensus: Dict[str, Any]
    books: List[Dict[str, Any]]


class Sport(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    name: Optional[str]
    is_team_sport: Optional[bool]
    leagues: List[LeagueSummary]


class SportsListResponse(TypedDict, total=False):
    sports: List[Sport]
    total: int


class Team(TypedDict, total=False):
    id: Optional[int]
    slug: Optional[str]
    name: Optional[str]
    short_name: Optional[str]
    abbreviation: Optional[str]
    sport: Optional[str]
    league: Optional[str]
    city: Optional[str]
    state: Optional[str]
    country_code: Optional[str]
    conference: Optional[str]
    division: Optional[str]
    venue: Optional[Dict[str, Any]]
    is_active: Optional[bool]


class TeamsListResponse(TypedDict, total=False):
    data: List[Team]
    has_more: bool
    next_after_id: Optional[int]


TrialKeyRequest = TypedDict(
    'TrialKeyRequest',
    {
        'cf-turnstile-response': str,
    },
    total=False,
)


class ValidationError(TypedDict, total=False):
    loc: List[Union[str, int]]
    msg: str
    type: str
    input: Any
    ctx: Dict[str, Any]


class WebhookCreateResponse(TypedDict, total=False):
    id: Optional[int]
    url: Optional[str]
    event_types: List[str]
    sport: Optional[str]
    event_id: Optional[int]
    is_active: Optional[bool]
    created_at: Optional[str]
    signing_secret: Optional[str]
    """Returned only on create — store it to verify Lumify-Signature."""


class WebhookDeleteResponse(TypedDict, total=False):
    deleted: bool
    id: Optional[int]


class WebhookDeliveryItem(TypedDict, total=False):
    id: Optional[int]
    event_type: Optional[str]
    event_id: Optional[int]
    attempt: Optional[int]
    parent_delivery_id: Optional[int]
    status_code: Optional[int]
    success: Optional[bool]
    error: Optional[str]
    given_up: Optional[bool]
    next_retry_at: Optional[str]
    delivered_at: Optional[str]


class WebhookDeliveryListResponse(TypedDict, total=False):
    data: List[WebhookDeliveryItem]
    next_after_id: Optional[int]


class WebhookListResponse(TypedDict, total=False):
    data: List[WebhookSubscription]
    total: int


class WebhookSubscription(TypedDict, total=False):
    id: Optional[int]
    url: Optional[str]
    event_types: List[str]
    sport: Optional[str]
    event_id: Optional[int]
    is_active: Optional[bool]
    created_at: Optional[str]
    signing_secret: Optional[str]
    """Returned only on create — store it to verify Lumify-Signature."""
